### ISSUE TITLE
PDF compilation

### ISSUE THREAD

**Issue by M4G13** [TheSheepGuy/Open_Higher_Maths#2]
**Getting auto PDF compilation**
Options:
- GitHub actions - needs investigation
- GitLab
  - Convert Fully
  - Use external CI feature, which I've set up [here](https://gitlab.com/msandreereid/Open_Higher_Maths) as a POC (Permanent link to file [here](https://gitlab.com/msandreereid/Open_Higher_Maths/-/jobs/artifacts/master/download?job=compile_pdf))
- There are other CI solutions but I don't know how to use them and would require more effort than it is worth
- Be boring and do it manually Zzz

**Comment by ettolrach** [comment]
I think it can definitely be fine with GitHub Actions, but I need to do some more looking into it. I didn't have the time today, but on Wednesday I'll have the time to definitely.

Also, I hope the PDF won't be copied into the repo itself, since otherwise it'll make one of the files in .git/ really huge.

**Comment by M4G13** [comment]
OK so I have it working with GitHub Actions but it runs for every commit and I can't find a way to only update when .tex files are updated.

Code is here
``` yaml
name: Build LaTeX document
on: push
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repo
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
      - name: Upload PDF to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.pdf
          asset_name: Higher_Maths.pdf
          tag: 1
          overwrite: true
```

This uploads the PDF to a release with tag 1 (has to be created before running).
